### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by djtruco** [wmantly/sshuttle-gui#3]
Hi, I'm interested on the project but I don't find instructions on how to run it. Could you provide those?

Thanks!

**Comment by wmantly** [comment]
Thank you for your interest in this project. Unfortunately, this project does almost nothing and stoped development when I meet my simplest goal. The "GUI" of the project is just a tray icon that is green when sshuttle is connected, red when its not, and yellow on error. The IP SSH host and address are even hardcoded in the code. They can be changed here https://github.com/wmantly/sshuttle-gui/blob/master/lib/process_sshuttle.js#L40 

This is a normal nodeJS project. After its cloned, `npm install` to install the nodeJS dependencies, then `npm start` to run it.

**Comment by djtruco** [comment]
Thank you for answering, I will play with it!
